import { describe, expect, it } from "vitest";
import {
  buildGoogleAdsDecisionSnapshotMetadata,
  normalizeGoogleAdsDecisionSnapshotPayload,
} from "@/lib/google-ads/decision-snapshot";

describe("Google Ads decision snapshot metadata", () => {
  it("builds Decision Snapshot V2 metadata with explicit primary/query/baseline fields", () => {
    const metadata = buildGoogleAdsDecisionSnapshotMetadata({
      analysisMode: "snapshot",
      asOfDate: "2026-04-08",
      selectedWindowKey: "operational_28d",
      historicalSupport: null,
      decisionSummaryTotals: {
        windowKey: "operational_28d",
        windowLabel: "operational 28d",
        spend: 1200,
        revenue: 4200,
        conversions: 35,
        roas: 3.5,
      },
      selectedRangeTotals: {
        windowKey: "custom",
        windowLabel: "selected 7d",
        spend: 250,
        revenue: 700,
        conversions: 5,
        roas: 2.8,
      },
      selectedRangeContext: null,
    });

    expect(metadata).toMatchObject({
      analysisMode: "snapshot",
      asOfDate: "2026-04-08",
      decisionEngineVersion: "v2",
      snapshotModel: "decision_snapshot_v2",
      selectedWindowKey: "operational_28d",
      primaryWindowKey: "operational_28d",
      queryWindowKey: "query_governance_56d",
      baselineWindowKey: "baseline_84d",
      maturityCutoffDays: 84,
      selectedRangeRole: "contextual_only",
      lagAdjustedEndDate: {
        available: false,
        value: null,
      },
      decisionSummaryTotals: {
        windowKey: "operational_28d",
        spend: 1200,
        revenue: 4200,
        conversions: 35,
        roas: 3.5,
      },
      selectedRangeTotals: {
        windowKey: "custom",
        windowLabel: "selected 7d",
        spend: 250,
        revenue: 700,
        conversions: 5,
        roas: 2.8,
      },
      canonicalWindowTotals: {
        spend: 1200,
        revenue: 4200,
        conversions: 35,
        roas: 3.5,
      },
    });
  });

  it("normalizes older payloads into the Decision Snapshot V2 shape", () => {
    const payload = normalizeGoogleAdsDecisionSnapshotPayload({
      advisorPayload: {
        summary: {
          headline: "headline",
          operatorNote: "note",
          demandMap: "map",
          topPriority: "priority",
          totalRecommendations: 0,
          actRecommendationCount: 0,
          accountState: "scaling_ready",
          accountOperatingMode: "mode",
          topConstraint: "constraint",
          topGrowthLever: "lever",
          recommendedFocusToday: "focus",
          watchouts: [],
          dataTrustSummary: "trust",
          campaignRoles: [],
        },
        recommendations: [
          {
            id: "legacy-query-governance",
            level: "account",
            type: "query_governance",
            strategyLayer: "Search Governance",
            decisionState: "act",
            decisionFamily: "waste_control",
            doBucket: "do_now",
            priority: "high",
            confidence: "high",
            dataTrust: "high",
            integrityState: "ready",
            supportStrength: "strong",
            actionability: "ready_now",
            reversibility: "high",
            title: "Legacy query governance",
            summary: "Legacy snapshot row",
            why: "Legacy snapshot why",
            decision: {
              decisionFamily: "waste_control",
              lane: "review",
              riskLevel: "low",
              blastRadius: "campaign",
              confidence: 0.88,
              windowsUsed: {
                healthWindow: "alarm_7d",
                primaryWindow: "operational_28d",
                queryWindow: "query_governance_56d",
                baselineWindow: "baseline_84d",
                maturityCutoffDays: 84,
              },
              whyNow: "Legacy why now",
              whyNot: [],
              blockers: [],
              validationPlan: ["Review next window."],
              rollbackPlan: ["Reverse manually in Google Ads."],
              evidenceSummary: "Legacy evidence summary",
              evidencePoints: [{ label: "Eligible", value: "1" }],
            },
            decisionNarrative: {
              whatHappened: "Legacy what happened",
              whyItHappened: "Legacy why happened",
              whatToDo: "Legacy what to do",
              risk: "Legacy risk",
              howToValidate: ["Review next window."],
              howToRollBack: "Reverse manually in Google Ads.",
            },
            whyNow: "Legacy why now",
            reasonCodes: ["legacy"],
            confidenceExplanation: "Legacy confidence",
            confidenceDegradationReasons: [],
            recommendedAction: "Add the exact negative manually.",
            potentialContribution: {
              label: "Waste recovery",
              impact: "medium",
              summary: "Recover waste without widening blast radius.",
              estimatedWasteRecoveryRange: "$20-$40",
            },
            impactBand: "medium",
            effortScore: "low",
            rollbackGuidance: "Reverse manually in Google Ads.",
            validationChecklist: ["Review next window."],
            blockers: [],
            rankScore: 10,
            rankExplanation: "Legacy rank",
            impactScore: 6,
            recommendationFingerprint: "legacy-fp",
            evidence: [{ label: "Eligible", value: "1" }],
            timeframeContext: {
              coreVerdict: "core",
              selectedRangeNote: "selected note",
              historicalSupport: "history",
            },
            negativeQueries: ["refund policy"],
            suppressedQueries: ["brand chairs"],
            suppressionReasons: ["branded_query"],
          },
        ],
        sections: [],
        clusters: [],
        metadata: {
          analysisMode: "snapshot",
          asOfDate: "2026-04-08",
          decisionEngineVersion: "v2",
          selectedWindowKey: "operational_28d",
          analysisWindows: {
            healthAlarmWindows: [],
            operationalWindow: {
              key: "operational_28d",
              label: "operational 28d",
              startDate: "2026-03-12",
              endDate: "2026-04-08",
              days: 28,
              role: "operational_decision",
            },
            queryGovernanceWindow: {
              key: "query_governance_56d",
              label: "query governance 56d",
              startDate: "2026-02-12",
              endDate: "2026-04-08",
              days: 56,
              role: "query_governance",
            },
            baselineWindow: {
              key: "baseline_84d",
              label: "baseline 84d",
              startDate: "2026-01-15",
              endDate: "2026-04-08",
              days: 84,
              role: "baseline",
            },
          },
          executionSurface: {
            mode: "operator_first_manual_plan",
            decisionEngineV2Enabled: true,
            writebackEnabled: false,
            mutateVerified: false,
            rollbackVerified: false,
            capabilityGateReason: "reason",
            summary: "summary",
          },
          historicalSupportAvailable: false,
          historicalSupport: null,
          selectedRangeTotals: {
            windowKey: "custom",
            windowLabel: "selected 7d",
            spend: 80,
            revenue: 200,
            conversions: 4,
            roas: 2.5,
          },
          canonicalWindowTotals: {
            spend: 100,
            revenue: 350,
            conversions: 12,
            roas: 3.5,
          },
          selectedRangeContext: null,
        },
      },
      analysisMode: "snapshot",
      asOfDate: "2026-04-08",
      selectedWindowKey: "operational_28d",
      historicalSupport: null,
    });

    expect(payload.metadata).toMatchObject({
      snapshotModel: "decision_snapshot_v2",
      primaryWindowKey: "operational_28d",
      queryWindowKey: "query_governance_56d",
      baselineWindowKey: "baseline_84d",
      selectedRangeRole: "contextual_only",
      decisionSummaryTotals: {
        windowKey: "operational_28d",
        spend: 100,
        revenue: 350,
        conversions: 12,
        roas: 3.5,
      },
      selectedRangeTotals: {
        windowKey: "custom",
        windowLabel: "selected 7d",
        spend: 80,
        revenue: 200,
        conversions: 4,
        roas: 2.5,
      },
      actionContract: {
        version: "google_ads_advisor_action_v2",
        source: "compatibility_derived",
      },
    });
    expect(payload.recommendations[0]?.operatorActionCard?.contractSource).toBe("compatibility_derived");
    expect(payload.recommendations[0]?.operatorActionCard?.exactChangePayload.kind).toBe("negative_keyword_cleanup");
  });

  it("keeps current v2 native snapshots marked as native on read", () => {
    const payload = normalizeGoogleAdsDecisionSnapshotPayload({
      advisorPayload: {
        summary: {
          headline: "headline",
          operatorNote: "note",
          demandMap: "map",
          topPriority: "priority",
          totalRecommendations: 0,
          actRecommendationCount: 0,
          accountState: "scaling_ready",
          accountOperatingMode: "mode",
          topConstraint: "constraint",
          topGrowthLever: "lever",
          recommendedFocusToday: "focus",
          watchouts: [],
          dataTrustSummary: "trust",
          campaignRoles: [],
        },
        recommendations: [],
        sections: [],
        clusters: [],
        metadata: {
          analysisMode: "snapshot",
          asOfDate: "2026-04-08",
          decisionEngineVersion: "v2",
          snapshotModel: "decision_snapshot_v2",
          selectedWindowKey: "operational_28d",
          primaryWindowKey: "operational_28d",
          queryWindowKey: "query_governance_56d",
          baselineWindowKey: "baseline_84d",
          maturityCutoffDays: 84,
          lagAdjustedEndDate: {
            available: false,
            value: null,
            note: null,
          },
          selectedRangeRole: "contextual_only",
          analysisWindows: {
            healthAlarmWindows: [],
            operationalWindow: {
              key: "operational_28d",
              label: "operational 28d",
              startDate: "2026-03-12",
              endDate: "2026-04-08",
              days: 28,
              role: "operational_decision",
            },
            queryGovernanceWindow: {
              key: "query_governance_56d",
              label: "query governance 56d",
              startDate: "2026-02-12",
              endDate: "2026-04-08",
              days: 56,
              role: "query_governance",
            },
            baselineWindow: {
              key: "baseline_84d",
              label: "baseline 84d",
              startDate: "2026-01-15",
              endDate: "2026-04-08",
              days: 84,
              role: "baseline",
            },
          },
          executionSurface: {
            mode: "operator_first_manual_plan",
            decisionEngineV2Enabled: true,
            writebackEnabled: false,
            mutateVerified: false,
            rollbackVerified: false,
            capabilityGateReason: "reason",
            summary: "summary",
          },
          historicalSupportAvailable: false,
          historicalSupport: null,
          decisionSummaryTotals: null,
          canonicalWindowTotals: null,
          selectedRangeContext: null,
          actionContract: {
            version: "google_ads_advisor_action_v2",
            source: "native",
            note: "Structured operator cards are the source of truth for this snapshot.",
          },
        },
      },
      analysisMode: "snapshot",
      asOfDate: "2026-04-08",
      selectedWindowKey: "operational_28d",
      historicalSupport: null,
    });

    expect(payload.metadata?.actionContract).toMatchObject({
      version: "google_ads_advisor_action_v2",
      source: "native",
    });
  });
});
