import {
  RELEASE_AUTHORITY_CANONICAL_DOC,
  resolveCommandCenterExecutionApplyFlagPosture,
  resolveCommandCenterExecutionPreviewFlagPosture,
  resolveCommandCenterWorkflowFlagPosture,
  resolveCreativeDecisionOsFlagPosture,
  resolveMetaDecisionOsFlagPosture,
} from "@/lib/release-authority/config";
import type { ReleaseAuthoritySurfaceDefinition } from "@/lib/release-authority/types";

function liveIfEnabled(input: {
  flagPosture: ReturnType<typeof resolveMetaDecisionOsFlagPosture> | null;
}) {
  return input.flagPosture?.mode === "enabled" ? "live" : "flagged";
}

export const RELEASE_AUTHORITY_SURFACES: ReleaseAuthoritySurfaceDefinition[] = [
  {
    id: "operating_mode",
    label: "Operating Mode",
    area: "commercial",
    repositoryState: "merged",
    runtimeState: "live",
    docsState: "current",
    references: [
      { kind: "page", path: "app/(dashboard)/platforms/meta/page.tsx", label: "Meta page" },
      { kind: "component", path: "components/meta/meta-operating-mode-card.tsx", label: "Meta operating mode card" },
      { kind: "component", path: "components/creatives/creative-commercial-context-card.tsx", label: "Creative commercial context" },
      { kind: "api", path: "app/api/business-operating-mode/route.ts", label: "Operating mode route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-02-operating-modes.md", label: "Phase 02 operating modes" },
    ],
    notes: [
      "Deterministic commercial-truth overlay remains live.",
      "No feature flag gates the current operating mode surface.",
    ],
  },
  {
    id: "recommendations",
    label: "Recommendations",
    area: "meta",
    repositoryState: "merged",
    runtimeState: "live",
    docsState: "current",
    references: [
      { kind: "page", path: "app/(dashboard)/platforms/meta/page.tsx", label: "Meta page" },
      { kind: "component", path: "components/meta/meta-account-recs.tsx", label: "Recommendations panel" },
      { kind: "api", path: "app/api/meta/recommendations/route.ts", label: "Recommendations route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-03-meta-decision-os.md", label: "Phase 03 Meta Decision OS" },
    ],
    notes: [
      "The compatibility route remains live, but the visible panel now renders action context derived from the Meta Decision OS authority snapshot.",
      "This surface no longer carries an independent decision voice.",
    ],
  },
  {
    id: "meta_decision_os",
    label: "Meta Decision OS",
    area: "meta",
    repositoryState: "merged",
    runtimeState: liveIfEnabled,
    docsState: "current",
    flagResolver: resolveMetaDecisionOsFlagPosture,
    references: [
      { kind: "page", path: "app/(dashboard)/platforms/meta/page.tsx", label: "Meta page" },
      { kind: "component", path: "components/meta/meta-decision-os.tsx", label: "Decision OS overview" },
      { kind: "api", path: "app/api/meta/decision-os/route.ts", label: "Meta Decision OS route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-03-meta-decision-os.md", label: "Phase 03 Meta Decision OS" },
      { kind: "doc", path: "docs/phase-03-meta-action-contract.md", label: "Phase 03 action contract" },
    ],
    notes: [
      "Current runtime posture is derived from the existing Meta Decision OS config helpers.",
      "Allowlist posture remains visible without exposing business IDs.",
      "GEO V2 uses dedicated country-only serving so GEO rows can stay live even when broader breakdown surfaces are partial.",
      "Meta Strategy Engine V2 adds additive policy metadata and a read-only winner scale candidate board without changing the execution subset.",
      "Additive creative linkage and profitable-truth-capped readiness are current when the surface is enabled.",
    ],
  },
  {
    id: "creative_decision_os",
    label: "Creative Decision OS",
    area: "creative",
    repositoryState: "merged",
    runtimeState: liveIfEnabled,
    docsState: "current",
    flagResolver: resolveCreativeDecisionOsFlagPosture,
    references: [
      { kind: "page", path: "app/(dashboard)/creatives/page.tsx", label: "Creatives page" },
      { kind: "component", path: "components/creatives/CreativeDecisionOsOverview.tsx", label: "Creative Decision OS overview" },
      { kind: "component", path: "components/creatives/CreativeDecisionOsDrawer.tsx", label: "Creative Decision OS drawer" },
      { kind: "api", path: "app/api/creatives/decision-os/route.ts", label: "Creative Decision OS route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-04-creative-decision-os.md", label: "Phase 04 creative decision OS" },
      { kind: "doc", path: "docs/phase-04-creative-action-contract.md", label: "Phase 04 action contract" },
      { kind: "doc", path: "docs/v2-08-historical-intelligence.md", label: "V2-08 historical intelligence" },
    ],
    notes: [
      "Creative Decision OS stays deterministic and read-only.",
      "The current baseline opens the surface in a dedicated resizable drawer with operator-review wording instead of a long inline page section.",
      "Additive economics floors, deployment compatibility, protected winners, and supply planning are current when the surface is enabled.",
      "Preview truth now exposes honest ready/degraded/missing review states and gates AI interpretation accordingly.",
      "A separate selected-period historical analysis panel is additive and analysis-only; it does not change Decision Signals or live decision authority.",
      "The surface is current only when the Creative Decision OS flag posture permits it.",
    ],
  },
  {
    id: "decision_signals",
    label: "Decision Signals",
    area: "creative",
    repositoryState: "merged",
    runtimeState: "live",
    docsState: "current",
    references: [
      { kind: "page", path: "app/(dashboard)/creatives/page.tsx", label: "Creatives page" },
      { kind: "component", path: "components/creatives/CreativeDetailExperience.tsx", label: "Creative detail experience" },
      { kind: "api", path: "app/api/creatives/decisions/route.ts", label: "Decision Signals route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-04-creative-action-contract.md", label: "Phase 04 action contract" },
    ],
    notes: [
      "Decision Signals remain the compatibility surface for deterministic creative actions.",
      "This phase does not change wording or action semantics.",
    ],
  },
  {
    id: "ai_commentary",
    label: "AI Commentary",
    area: "creative",
    repositoryState: "merged",
    runtimeState: "live",
    docsState: "current",
    references: [
      { kind: "page", path: "app/(dashboard)/creatives/page.tsx", label: "Creatives page" },
      { kind: "component", path: "components/creatives/CreativeDetailExperience.tsx", label: "Creative detail experience" },
      { kind: "api", path: "app/api/ai/creatives/commentary/route.ts", label: "AI commentary route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-04-creative-decision-os.md", label: "Phase 04 creative decision OS" },
    ],
    notes: [
      "AI commentary remains bounded interpretation only.",
      "This authority layer only inventories the surface; it does not change provenance rules.",
    ],
  },
  {
    id: "command_center_workflow",
    label: "Command Center Workflow",
    area: "workflow",
    repositoryState: "merged",
    runtimeState: liveIfEnabled,
    docsState: "current",
    flagResolver: resolveCommandCenterWorkflowFlagPosture,
    references: [
      { kind: "page", path: "app/(dashboard)/command-center/page.tsx", label: "Command Center page" },
      { kind: "component", path: "components/command-center/CommandCenterDashboard.tsx", label: "Command Center dashboard" },
      { kind: "api", path: "app/api/command-center/route.ts", label: "Command Center route" },
      { kind: "api", path: "app/api/command-center/actions/route.ts", label: "Workflow mutation route" },
      { kind: "api", path: "app/api/command-center/actions/batch/route.ts", label: "Batch mutation route" },
      { kind: "api", path: "app/api/command-center/feedback/route.ts", label: "Feedback route" },
      { kind: "api", path: "app/api/command-center/views/route.ts", label: "Saved views route" },
      { kind: "api", path: "app/api/command-center/handoffs/route.ts", label: "Handoffs route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-05-command-center.md", label: "Phase 05 command center" },
      { kind: "doc", path: "docs/phase-05-action-queue-contract.md", label: "Phase 05 action queue contract" },
      { kind: "doc", path: "docs/v2-06-command-center-throughput.md", label: "V2-06 throughput baseline" },
      { kind: "doc", path: "docs/v2-06-release-checklist.md", label: "V2-06 release checklist" },
      { kind: "doc", path: "docs/v2-06-rollout-runbook.md", label: "V2-06 rollout runbook" },
      { kind: "doc", path: "docs/v2-08-historical-intelligence.md", label: "V2-08 historical intelligence" },
    ],
    notes: [
      "Workflow state remains additive on top of deterministic decision sources.",
      "Current posture is resolved from the Command Center config helpers.",
      "Meta GEO intake only queues material queue-eligible GEO rows; pooled/watchlist GEOs stay out of the default queue.",
      "The default queue is bounded server-side and exposes overflow, owner workload, and shift digest summaries.",
      "Structured feedback and status-only batch actions are current workflow surfaces and remain retry-safe.",
      "A separate historical intelligence panel now summarizes selected-period campaign families, queue quality, degraded guidance, and deterministic calibration suggestions.",
    ],
  },
  {
    id: "command_center_execution_preview",
    label: "Command Center Execution Preview",
    area: "execution",
    repositoryState: "merged",
    runtimeState: liveIfEnabled,
    docsState: "current",
    flagResolver: resolveCommandCenterExecutionPreviewFlagPosture,
    references: [
      { kind: "page", path: "app/(dashboard)/command-center/page.tsx", label: "Command Center page" },
      { kind: "component", path: "components/command-center/CommandCenterDashboard.tsx", label: "Execution panel" },
      { kind: "api", path: "app/api/command-center/execution/route.ts", label: "Execution preview route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-06-safe-execution-layer.md", label: "Phase 06 safe execution layer" },
      { kind: "doc", path: "docs/phase-06-executor-contract.md", label: "Phase 06 execution contract" },
      { kind: "doc", path: "docs/v2-07-safe-execution-proof.md", label: "V2-07 safe execution proof" },
    ],
    notes: [
      "Preview-first execution posture is tracked separately from apply/rollback authority.",
      "This surface is operator-visible only when the execution preview flag is enabled.",
      "The current preview baseline exposes an explicit capability registry, preflight drift checks, post-apply validation status, and rollback-truth copy without widening provider-backed scope.",
    ],
  },
  {
    id: "command_center_execution_apply_rollback",
    label: "Command Center Apply & Rollback",
    area: "execution",
    repositoryState: "merged",
    runtimeState: liveIfEnabled,
    docsState: "current",
    flagResolver: resolveCommandCenterExecutionApplyFlagPosture,
    references: [
      { kind: "page", path: "app/(dashboard)/command-center/page.tsx", label: "Command Center page" },
      { kind: "component", path: "components/command-center/CommandCenterDashboard.tsx", label: "Execution panel" },
      { kind: "api", path: "app/api/command-center/execution/apply/route.ts", label: "Apply route" },
      { kind: "api", path: "app/api/command-center/execution/rollback/route.ts", label: "Rollback route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-06-safe-execution-layer.md", label: "Phase 06 safe execution layer" },
      { kind: "doc", path: "docs/phase-06-rollout-runbook.md", label: "Phase 06 rollout runbook" },
      { kind: "doc", path: "docs/v2-07-safe-execution-proof.md", label: "V2-07 safe execution proof" },
      { kind: "doc", path: "docs/v2-07-release-checklist.md", label: "V2-07 release checklist" },
      { kind: "doc", path: "docs/v2-07-rollout-runbook.md", label: "V2-07 rollout runbook" },
    ],
    notes: [
      "Apply and rollback authority stay explicit and canary-gated.",
      "A disabled or allowlist-only apply posture is intentional and not treated as hidden.",
      "The apply subset stays kill-switch-aware, post-validated, and backed by immutable provider diff evidence.",
      "Duplicate client mutation IDs now replay terminal results or stop with a non-dispatching conflict instead of issuing a second provider write.",
    ],
  },
  {
    id: "copies",
    label: "/copies",
    area: "copy",
    repositoryState: "merged",
    runtimeState: "live",
    docsState: "current",
    references: [
      { kind: "page", path: "app/(dashboard)/copies/page.tsx", label: "Copies page" },
      { kind: "api", path: "app/api/meta/copies/route.ts", label: "Copies route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-04-creative-decision-os.md", label: "Phase 04 creative decision OS" },
      { kind: "doc", path: "docs/phase-05-command-center.md", label: "Phase 05 command center" },
      { kind: "doc", path: "docs/phase-06-safe-execution-layer.md", label: "Phase 06 safe execution layer" },
    ],
    notes: [
      "The surface remains live and intentionally unchanged in this phase.",
      "Authority coverage is explicit so /copies cannot disappear into baseline ambiguity.",
    ],
  },
  {
    id: "legacy_meta_alias",
    label: "Legacy Meta Alias",
    area: "legacy",
    repositoryState: "merged",
    runtimeState: "legacy",
    docsState: "current",
    references: [
      { kind: "alias", path: "app/(dashboard)/meta/page.tsx", label: "/meta -> /platforms/meta" },
      { kind: "page", path: "app/(dashboard)/platforms/meta/page.tsx", label: "Canonical Meta page" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
    ],
    notes: [
      "The legacy alias remains intentionally shipped as a redirect.",
      "It is marked legacy rather than hidden so drift stays explicit.",
    ],
  },
];
