export const V21_PRIMARY_DECISIONS = [
  "Scale",
  "Cut",
  "Refresh",
  "Protect",
  "Test More",
  "Diagnose",
] as const;

export const V21_BUYER_ACTIONS = [
  "scale",
  "cut",
  "refresh",
  "protect",
  "test_more",
  "watch_launch",
  "fix_delivery",
  "fix_policy",
  "diagnose_data",
] as const;

export const V21_ACTIONABILITIES = [
  "direct",
  "review_only",
  "blocked",
  "diagnose",
] as const;

export const V21_PROBLEM_CLASSES = [
  "performance",
  "creative",
  "fatigue",
  "delivery",
  "policy",
  "data_quality",
  "campaign_context",
  "insufficient_signal",
  "launch_monitoring",
] as const;

export const V21_PRIORITY_BANDS = ["critical", "high", "medium", "low"] as const;
export const V21_CONFIDENCE_BANDS = ["high", "medium", "low"] as const;
export const V21_MATURITY_BANDS = [
  "too_early",
  "learning",
  "actionable",
  "mature",
] as const;

export type V21PrimaryDecision = (typeof V21_PRIMARY_DECISIONS)[number];
export type V21BuyerAction = (typeof V21_BUYER_ACTIONS)[number];
export type V21Actionability = (typeof V21_ACTIONABILITIES)[number];
export type V21ProblemClass = (typeof V21_PROBLEM_CLASSES)[number];
export type V21PriorityBand = (typeof V21_PRIORITY_BANDS)[number];
export type V21ConfidenceBand = (typeof V21_CONFIDENCE_BANDS)[number];
export type V21MaturityBand = (typeof V21_MATURITY_BANDS)[number];

export type V21SafeFallback = V21BuyerAction | "disable_aggregate";

export interface CreativeDecisionCenterV21GoldenCase {
  caseId: `GC-${string}`;
  inputSummary: string;
  expectedPrimaryDecision: V21PrimaryDecision;
  expectedBuyerAction: V21BuyerAction;
  expectedActionability: V21Actionability;
  expectedProblemClass: V21ProblemClass;
  expectedPriorityBand: V21PriorityBand;
  expectedConfidenceBand: V21ConfidenceBand;
  expectedTopReasonTag: string;
  expectedMaturity: V21MaturityBand;
  expectedSafeFallbackIfDataMissing: V21SafeFallback;
  scope: "row" | "aggregate_only";
}

// Canonical PR2 fixtures copied from docs/creative-decision-center/GOLDEN_CASES.md.
// They are contract fixtures only: they do not exercise or change production resolver behavior.
export const CREATIVE_DECISION_CENTER_V21_GOLDEN_CASES = [
  {
    caseId: "GC-001",
    inputSummary: "active ad + active campaign/adset + 24h spend 0 + impressions 0",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "fix_delivery",
    expectedActionability: "diagnose",
    expectedProblemClass: "delivery",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "medium",
    expectedTopReasonTag: "active_no_spend_24h",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-002",
    inputSummary: "no spend but campaign paused",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "diagnose_data",
    expectedActionability: "diagnose",
    expectedProblemClass: "campaign_context",
    expectedPriorityBand: "medium",
    expectedConfidenceBand: "medium",
    expectedTopReasonTag: "campaign_paused",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-003",
    inputSummary: "adset paused",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "diagnose_data",
    expectedActionability: "diagnose",
    expectedProblemClass: "campaign_context",
    expectedPriorityBand: "medium",
    expectedConfidenceBand: "medium",
    expectedTopReasonTag: "adset_paused",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-004",
    inputSummary: "disapproved creative",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "fix_policy",
    expectedActionability: "diagnose",
    expectedProblemClass: "policy",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "high",
    expectedTopReasonTag: "disapproved_or_limited",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-005",
    inputSummary: "limited delivery with reason",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "fix_policy",
    expectedActionability: "diagnose",
    expectedProblemClass: "policy",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "high",
    expectedTopReasonTag: "disapproved_or_limited",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-006",
    inputSummary: "policy status unknown",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "diagnose_data",
    expectedActionability: "diagnose",
    expectedProblemClass: "data_quality",
    expectedPriorityBand: "medium",
    expectedConfidenceBand: "low",
    expectedTopReasonTag: "missing_policy_status",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-007",
    inputSummary: "new launch under 48h with low spend",
    expectedPrimaryDecision: "Test More",
    expectedBuyerAction: "watch_launch",
    expectedActionability: "review_only",
    expectedProblemClass: "launch_monitoring",
    expectedPriorityBand: "medium",
    expectedConfidenceBand: "medium",
    expectedTopReasonTag: "new_launch_window",
    expectedMaturity: "too_early",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-008",
    inputSummary: "new launch under 72h with enough spend but no purchase",
    expectedPrimaryDecision: "Test More",
    expectedBuyerAction: "watch_launch",
    expectedActionability: "review_only",
    expectedProblemClass: "launch_monitoring",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "medium",
    expectedTopReasonTag: "new_launch_window",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-009",
    inputSummary: "new launch with severe overspend and no purchases",
    expectedPrimaryDecision: "Test More",
    expectedBuyerAction: "watch_launch",
    expectedActionability: "review_only",
    expectedProblemClass: "launch_monitoring",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "medium",
    expectedTopReasonTag: "new_launch_severe_spend_no_purchase",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-010",
    inputSummary: "mature high-spend loser",
    expectedPrimaryDecision: "Cut",
    expectedBuyerAction: "cut",
    expectedActionability: "review_only",
    expectedProblemClass: "performance",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "high",
    expectedTopReasonTag: "severe_sustained_loser",
    expectedMaturity: "mature",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-011",
    inputSummary: "mature high-confidence winner",
    expectedPrimaryDecision: "Scale",
    expectedBuyerAction: "scale",
    expectedActionability: "review_only",
    expectedProblemClass: "performance",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "high",
    expectedTopReasonTag: "strong_relative_winner",
    expectedMaturity: "mature",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-012",
    inputSummary: "winner entering fatigue",
    expectedPrimaryDecision: "Refresh",
    expectedBuyerAction: "refresh",
    expectedActionability: "review_only",
    expectedProblemClass: "fatigue",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "high",
    expectedTopReasonTag: "fatigue_composite",
    expectedMaturity: "mature",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-013",
    inputSummary: "CTR down but frequency flat and CPM flat",
    expectedPrimaryDecision: "Test More",
    expectedBuyerAction: "test_more",
    expectedActionability: "review_only",
    expectedProblemClass: "insufficient_signal",
    expectedPriorityBand: "medium",
    expectedConfidenceBand: "medium",
    expectedTopReasonTag: "partial_fatigue_signal",
    expectedMaturity: "actionable",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-014",
    inputSummary: "frequency up but CTR stable",
    expectedPrimaryDecision: "Test More",
    expectedBuyerAction: "test_more",
    expectedActionability: "review_only",
    expectedProblemClass: "insufficient_signal",
    expectedPriorityBand: "medium",
    expectedConfidenceBand: "medium",
    expectedTopReasonTag: "partial_fatigue_signal",
    expectedMaturity: "actionable",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-015",
    inputSummary: "CPM up but CPA/ROAS stable",
    expectedPrimaryDecision: "Test More",
    expectedBuyerAction: "test_more",
    expectedActionability: "review_only",
    expectedProblemClass: "insufficient_signal",
    expectedPriorityBand: "medium",
    expectedConfidenceBand: "medium",
    expectedTopReasonTag: "partial_fatigue_signal",
    expectedMaturity: "actionable",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-016",
    inputSummary: "benchmark missing",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "diagnose_data",
    expectedActionability: "diagnose",
    expectedProblemClass: "data_quality",
    expectedPriorityBand: "medium",
    expectedConfidenceBand: "low",
    expectedTopReasonTag: "benchmark_missing",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-017",
    inputSummary: "benchmark weak",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "diagnose_data",
    expectedActionability: "diagnose",
    expectedProblemClass: "data_quality",
    expectedPriorityBand: "medium",
    expectedConfidenceBand: "low",
    expectedTopReasonTag: "weak_benchmark",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-018",
    inputSummary: "stale data",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "diagnose_data",
    expectedActionability: "diagnose",
    expectedProblemClass: "data_quality",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "low",
    expectedTopReasonTag: "stale_data",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-019",
    inputSummary: "attribution/truth missing",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "diagnose_data",
    expectedActionability: "diagnose",
    expectedProblemClass: "data_quality",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "low",
    expectedTopReasonTag: "truth_missing",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-020",
    inputSummary: "tracking drop suspected",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "diagnose_data",
    expectedActionability: "diagnose",
    expectedProblemClass: "data_quality",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "low",
    expectedTopReasonTag: "tracking_drop_suspected",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-021",
    inputSummary: "high priority but low confidence delivery issue",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "diagnose_data",
    expectedActionability: "diagnose",
    expectedProblemClass: "data_quality",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "low",
    expectedTopReasonTag: "missing_delivery_proof",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-022",
    inputSummary: "low maturity but high priority policy issue",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "fix_policy",
    expectedActionability: "diagnose",
    expectedProblemClass: "policy",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "high",
    expectedTopReasonTag: "disapproved_or_limited",
    expectedMaturity: "too_early",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-023",
    inputSummary: "mature data but low confidence due to attribution degradation",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "diagnose_data",
    expectedActionability: "diagnose",
    expectedProblemClass: "data_quality",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "low",
    expectedTopReasonTag: "truth_degraded",
    expectedMaturity: "mature",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-024",
    inputSummary: "active creative with spend but zero impressions anomaly",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "diagnose_data",
    expectedActionability: "diagnose",
    expectedProblemClass: "data_quality",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "low",
    expectedTopReasonTag: "spend_without_impressions",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-025",
    inputSummary: "high CTR but poor CVR / landing issue",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "diagnose_data",
    expectedActionability: "diagnose",
    expectedProblemClass: "performance",
    expectedPriorityBand: "medium",
    expectedConfidenceBand: "medium",
    expectedTopReasonTag: "landing_or_cvr_issue",
    expectedMaturity: "actionable",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-026",
    inputSummary: "strong ROAS but tiny spend, not mature",
    expectedPrimaryDecision: "Test More",
    expectedBuyerAction: "test_more",
    expectedActionability: "review_only",
    expectedProblemClass: "insufficient_signal",
    expectedPriorityBand: "medium",
    expectedConfidenceBand: "medium",
    expectedTopReasonTag: "tiny_spend_winner",
    expectedMaturity: "too_early",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-027",
    inputSummary: "strong CPA but low purchase count, not scalable yet",
    expectedPrimaryDecision: "Test More",
    expectedBuyerAction: "test_more",
    expectedActionability: "review_only",
    expectedProblemClass: "insufficient_signal",
    expectedPriorityBand: "medium",
    expectedConfidenceBand: "medium",
    expectedTopReasonTag: "low_purchase_count",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-028",
    inputSummary: "top 3 fatigue cluster",
    expectedPrimaryDecision: "Refresh",
    expectedBuyerAction: "refresh",
    expectedActionability: "review_only",
    expectedProblemClass: "fatigue",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "high",
    expectedTopReasonTag: "fatigue_composite",
    expectedMaturity: "mature",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-029",
    inputSummary: "no new winner in 7 days",
    expectedPrimaryDecision: "Protect",
    expectedBuyerAction: "protect",
    expectedActionability: "review_only",
    expectedProblemClass: "performance",
    expectedPriorityBand: "medium",
    expectedConfidenceBand: "medium",
    expectedTopReasonTag: "winner_gap_aggregate_only",
    expectedMaturity: "mature",
    expectedSafeFallbackIfDataMissing: "disable_aggregate",
    scope: "aggregate_only",
  },
  {
    caseId: "GC-030",
    inputSummary: "approved but unused creative exists",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "diagnose_data",
    expectedActionability: "diagnose",
    expectedProblemClass: "campaign_context",
    expectedPriorityBand: "medium",
    expectedConfidenceBand: "medium",
    expectedTopReasonTag: "unused_approved_aggregate_only",
    expectedMaturity: "too_early",
    expectedSafeFallbackIfDataMissing: "disable_aggregate",
    scope: "aggregate_only",
  },
  {
    caseId: "GC-031",
    inputSummary: "family winner aging with no backup variants",
    expectedPrimaryDecision: "Protect",
    expectedBuyerAction: "protect",
    expectedActionability: "review_only",
    expectedProblemClass: "performance",
    expectedPriorityBand: "medium",
    expectedConfidenceBand: "medium",
    expectedTopReasonTag: "backup_variant_aggregate_only",
    expectedMaturity: "mature",
    expectedSafeFallbackIfDataMissing: "disable_aggregate",
    scope: "aggregate_only",
  },
  {
    caseId: "GC-032",
    inputSummary: "old challenger says scale_hard but V2 says Test More",
    expectedPrimaryDecision: "Test More",
    expectedBuyerAction: "test_more",
    expectedActionability: "review_only",
    expectedProblemClass: "insufficient_signal",
    expectedPriorityBand: "medium",
    expectedConfidenceBand: "medium",
    expectedTopReasonTag: "low_evidence",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-033",
    inputSummary: "operator surface says act_now but V2 says Diagnose",
    expectedPrimaryDecision: "Diagnose",
    expectedBuyerAction: "diagnose_data",
    expectedActionability: "diagnose",
    expectedProblemClass: "data_quality",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "low",
    expectedTopReasonTag: "truth_degraded",
    expectedMaturity: "learning",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-034",
    inputSummary: "old V1 stable_winner maps to V2 Protect",
    expectedPrimaryDecision: "Protect",
    expectedBuyerAction: "protect",
    expectedActionability: "review_only",
    expectedProblemClass: "performance",
    expectedPriorityBand: "medium",
    expectedConfidenceBand: "high",
    expectedTopReasonTag: "stable_winner",
    expectedMaturity: "mature",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
  {
    caseId: "GC-035",
    inputSummary: "old V1 fatigued_winner maps to V2 Refresh",
    expectedPrimaryDecision: "Refresh",
    expectedBuyerAction: "refresh",
    expectedActionability: "review_only",
    expectedProblemClass: "fatigue",
    expectedPriorityBand: "high",
    expectedConfidenceBand: "high",
    expectedTopReasonTag: "fatigue_composite",
    expectedMaturity: "mature",
    expectedSafeFallbackIfDataMissing: "diagnose_data",
    scope: "row",
  },
] as const satisfies readonly CreativeDecisionCenterV21GoldenCase[];
