import { NextRequest, NextResponse } from "next/server";
import { requireBusinessAccess } from "@/lib/access";
import { getOpenAI } from "@/lib/openai";
import type { AiCreativeDecision, CreativeRuleReportPayload } from "@/src/services";

const MODEL = "gpt-5-nano";

interface RequestPayload {
  businessId?: string;
  currency?: string;
  report?: CreativeRuleReportPayload;
}

interface CommentaryPayload {
  headline: string;
  summary: string;
  opportunities: string[];
  risks: string[];
  nextActions: string[];
}

const SYSTEM_PROMPT = `You are a senior performance marketing strategist.

You will receive a deterministic creative classification report generated by a rule engine.
Your job is NOT to re-classify; your job is to interpret the report in a practical and actionable way.

Rules:
- Stay grounded in the given report only.
- Do not invent new metrics, thresholds, or hidden data.
- Keep language concise and operator-friendly.
- If confidence is low, explicitly mention uncertainty and suggest validation steps.
- Return ONLY valid JSON matching the required schema.`;

function sanitizeErrorMessage(input: string): string {
  const normalized = input.toLowerCase();
  if (normalized.includes("api key") && normalized.includes("not set")) {
    return "AI service is not configured (missing API key).";
  }
  if (normalized.includes("incorrect api key") || normalized.includes("invalid_api_key")) {
    return "AI service is not configured correctly (invalid API key).";
  }
  if (normalized.includes("rate limit") || normalized.includes("quota")) {
    return "AI service is temporarily rate limited. Please try again shortly.";
  }
  return "AI commentary generation failed. Showing rule-based summary.";
}

function isValidAction(action: unknown): action is AiCreativeDecision["action"] {
  return (
    action === "scale_hard" ||
    action === "scale" ||
    action === "watch" ||
    action === "test_more" ||
    action === "pause" ||
    action === "kill"
  );
}

function isValidReport(report: unknown): report is CreativeRuleReportPayload {
  if (!report || typeof report !== "object") return false;
  const source = report as Partial<CreativeRuleReportPayload>;
  if (typeof source.creativeId !== "string" || source.creativeId.length === 0) return false;
  if (typeof source.creativeName !== "string" || source.creativeName.length === 0) return false;
  if (!isValidAction(source.action)) return false;
  if (typeof source.score !== "number" || !Number.isFinite(source.score)) return false;
  if (typeof source.confidence !== "number" || !Number.isFinite(source.confidence)) return false;
  if (typeof source.summary !== "string") return false;
  if (!source.accountContext || typeof source.accountContext !== "object") return false;
  if (!Array.isArray(source.factors)) return false;
  return true;
}

function buildFallbackCommentary(report: CreativeRuleReportPayload): CommentaryPayload {
  const positives = report.factors
    .filter((factor) => factor.impact === "positive")
    .slice(0, 3)
    .map((factor) => `${factor.label}: ${factor.reason}`);
  const risks = report.factors
    .filter((factor) => factor.impact === "negative")
    .slice(0, 3)
    .map((factor) => `${factor.label}: ${factor.reason}`);

  const summary =
    report.summary.trim().length > 0
      ? report.summary.trim()
      : `Rule engine scored this creative ${report.score}/100 with ${Math.round(report.confidence * 100)}% confidence.`;

  return {
    headline: `Analysis interpretation: ${report.action.replace("_", " ").toUpperCase()}`,
    summary,
    opportunities: positives.length > 0 ? positives : ["No clear upside factors were detected by the scoring model."],
    risks: risks.length > 0 ? risks : ["No major downside factors were flagged by the scoring model."],
    nextActions:
      report.action === "scale_hard"
        ? [
            "Increase budget in controlled steps and monitor ROAS drift daily.",
            "Duplicate this concept to adjacent audiences with guardrails.",
          ]
        : report.action === "scale"
          ? [
              "Scale gradually while validating CPA stability over 72 hours.",
              "Keep one challenger test live to protect against fatigue.",
            ]
          : report.action === "pause" || report.action === "kill"
            ? [
                "Stop incremental spend and redirect budget to top performers.",
                "Launch a replacement concept with a meaningfully different angle.",
              ]
            : [
                "Keep spend controlled until confidence improves.",
                "Re-evaluate after additional conversion volume.",
              ],
  };
}

function buildUserPrompt(report: CreativeRuleReportPayload, currency: string): string {
  return JSON.stringify({
    task: "Interpret this rule-engine creative decision report for a media buyer.",
    outputSchema: {
      headline: "string, max 10 words",
      summary: "string, 1-2 sentences",
      opportunities: "string[2..3]",
      risks: "string[2..3]",
      nextActions: "string[3]",
    },
    constraints: [
      "Use only information present in the report.",
      "Do not repeat identical points across sections.",
      "Make nextActions concrete and operational.",
    ],
    currency,
    report,
  });
}

function normalizeCommentary(payload: unknown, fallback: CommentaryPayload): CommentaryPayload {
  if (!payload || typeof payload !== "object") return fallback;
  const source = payload as Partial<CommentaryPayload>;

  const toList = (value: unknown, minCount: number, maxCount: number, backup: string[]): string[] => {
    if (!Array.isArray(value)) return backup;
    const normalized = value
      .filter((item): item is string => typeof item === "string")
      .map((item) => item.trim())
      .filter((item) => item.length > 0)
      .slice(0, maxCount);
    return normalized.length >= minCount ? normalized : backup;
  };

  return {
    headline: typeof source.headline === "string" && source.headline.trim().length > 0 ? source.headline.trim() : fallback.headline,
    summary: typeof source.summary === "string" && source.summary.trim().length > 0 ? source.summary.trim() : fallback.summary,
    opportunities: toList(source.opportunities, 2, 3, fallback.opportunities),
    risks: toList(source.risks, 2, 3, fallback.risks),
    nextActions: toList(source.nextActions, 3, 3, fallback.nextActions),
  };
}

export async function POST(request: NextRequest) {
  const payload = (await request.json().catch(() => null)) as RequestPayload | null;
  const businessId = payload?.businessId ?? null;

  const access = await requireBusinessAccess({ request, businessId });
  if ("error" in access) return access.error;

  const report = payload?.report;
  const currency = payload?.currency ?? "USD";

  if (!isValidReport(report)) {
    return NextResponse.json(
      {
        ok: false,
        error: "invalid_report",
        message: "A valid rule report payload is required.",
      },
      { status: 400 }
    );
  }

  const fallback = buildFallbackCommentary(report);

  try {
    const openai = getOpenAI();
    const response = await openai.chat.completions.create({
      model: MODEL,
      temperature: 0.2,
      max_tokens: 700,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: buildUserPrompt(report, currency) },
      ],
    });

    const content = response.choices[0]?.message?.content ?? "";
    const parsed = JSON.parse(content || "{}");

    return NextResponse.json({
      ok: true,
      source: "ai",
      commentary: normalizeCommentary(parsed, fallback),
      warning: null,
    });
  } catch (error) {
    const raw = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({
      ok: true,
      source: "fallback",
      commentary: fallback,
      warning: sanitizeErrorMessage(raw),
    });
  }
}
