import { NextRequest, NextResponse } from "next/server";
import { requireBusinessAccess } from "@/lib/access";
import { getOpenAI } from "@/lib/openai";
import { isDemoBusinessId, getDemoAiCreativeCommentary } from "@/lib/demo-business";
import {
  getAiNarrativeLanguage,
  getNativeNarrativeStyleInstruction,
  getNonTranslatableTermsInstruction,
  type AppLanguage,
} from "@/lib/i18n";
import { resolveRequestLanguage } from "@/lib/request-language";
import type { AiCreativeDecision, CreativeRuleReportPayload } from "@/src/services";

const MODEL = "gpt-5-nano";

interface RequestPayload {
  businessId?: string;
  currency?: string;
  report?: CreativeRuleReportPayload;
}

interface CommentaryPayload {
  headline: string;
  summary: string;
  opportunities: string[];
  risks: string[];
  nextActions: string[];
}

interface OpenAiLikeError {
  status?: number;
  code?: string;
  type?: string;
  message?: string;
  error?: {
    code?: string;
    type?: string;
    message?: string;
  };
}

function getSystemPrompt(language: AppLanguage) {
  return `You are a senior performance marketing strategist.

You will receive a deterministic creative classification report generated by a rule engine.
Your job is NOT to re-classify; your job is to interpret the report in a practical and actionable way.

Rules:
- Stay grounded in the given report only.
- Do not invent new metrics, thresholds, or hidden data.
- Keep language concise and operator-friendly.
- Write all narrative strings in ${getAiNarrativeLanguage(language)}.
- ${getNativeNarrativeStyleInstruction(language)}
- ${getNonTranslatableTermsInstruction(language)}
- If confidence is low, explicitly mention uncertainty and suggest validation steps.
- Return ONLY valid JSON matching the required schema.`;
}

function sanitizeErrorMessage(input: string, language: AppLanguage): string {
  const normalized = input.toLowerCase();
  if (normalized.includes("unsupported_parameter")) {
    return language === "tr"
      ? "AI servisi bu model/hesap için bir istek parametresini reddetti."
      : "AI service rejected one request parameter for this model/account.";
  }
  if (normalized.includes("api key") && normalized.includes("not set")) {
    return language === "tr"
      ? "AI servisi yapılandırılmamış (API key eksik)."
      : "AI service is not configured (missing API key).";
  }
  if (normalized.includes("incorrect api key") || normalized.includes("invalid_api_key")) {
    return language === "tr"
      ? "AI servisi doğru yapılandırılmamış (geçersiz API key)."
      : "AI service is not configured correctly (invalid API key).";
  }
  if (normalized.includes("rate limit") || normalized.includes("quota")) {
    return language === "tr"
      ? "AI servisi gecici olarak oran sinirina takildi. Lütfen kisa sure sonra tekrar deneyin."
      : "AI service is temporarily rate limited. Please try again shortly.";
  }
  if (normalized.includes("model") && normalized.includes("not")) {
    return language === "tr"
      ? "Yapilandirilan AI modeli bu API key/hesap için kullanilabilir degil."
      : "Configured AI model is not available for this API key/account.";
  }
  if (normalized.includes("unauthorized") || normalized.includes("authentication")) {
    return language === "tr"
      ? "Yapilandirilan API key için AI servis kimlik doğrulamasi başarısız oldu."
      : "AI service authentication failed for the configured API key.";
  }
  if (normalized.includes("timeout") || normalized.includes("timed out")) {
    return language === "tr"
      ? "AI servisinde yorum uretilirken zaman asimi olüstu."
      : "AI service timed out while generating commentary.";
  }
  return language === "tr"
    ? "AI yorum üretimi başarısız oldu. Kural tabanli özet gösteriliyor."
    : "AI commentary generation failed. Showing rule-based summary.";
}

function isUnsupportedParameterError(error: unknown): boolean {
  if (!error || typeof error !== "object") return false;
  const source = error as OpenAiLikeError;
  const code = source.code ?? source.error?.code ?? "";
  const message =
    typeof source.message === "string"
      ? source.message
      : typeof source.error?.message === "string"
        ? source.error.message
        : "";
  const normalizedMessage = message.toLowerCase();
  return code === "unsupported_parameter" || normalizedMessage.includes("unsupported_parameter");
}

function parseCommentaryJson(content: string): unknown {
  const trimmed = content.trim();
  if (!trimmed) return {};
  try {
    return JSON.parse(trimmed);
  } catch {
    const first = trimmed.indexOf("{");
    const last = trimmed.lastIndexOf("}");
    if (first >= 0 && last > first) {
      const candidate = trimmed.slice(first, last + 1);
      try {
        return JSON.parse(candidate);
      } catch {
        return {};
      }
    }
    return {};
  }
}

function getErrorDetail(error: unknown): string {
  if (!error || typeof error !== "object") return "unknown_error";
  const candidate = error as {
    status?: number;
    code?: string;
    type?: string;
    error?: { code?: string; type?: string };
  };
  const statusPart = typeof candidate.status === "number" ? `status_${candidate.status}` : null;
  const codePart =
    typeof candidate.code === "string"
      ? candidate.code
      : typeof candidate.error?.code === "string"
        ? candidate.error.code
        : null;
  const typePart =
    typeof candidate.type === "string"
      ? candidate.type
      : typeof candidate.error?.type === "string"
        ? candidate.error.type
        : null;
  return [statusPart, codePart, typePart].filter(Boolean).join("|") || "unknown_error";
}

function isValidAction(action: unknown): action is AiCreativeDecision["action"] {
  return (
    action === "scale_hard" ||
    action === "scale" ||
    action === "watch" ||
    action === "test_more" ||
    action === "pause" ||
    action === "kill"
  );
}

function isValidReport(report: unknown): report is CreativeRuleReportPayload {
  if (!report || typeof report !== "object") return false;
  const source = report as Partial<CreativeRuleReportPayload>;
  if (typeof source.creativeId !== "string" || source.creativeId.length === 0) return false;
  if (typeof source.creativeName !== "string" || source.creativeName.length === 0) return false;
  if (!isValidAction(source.action)) return false;
  if (typeof source.score !== "number" || !Number.isFinite(source.score)) return false;
  if (typeof source.confidence !== "number" || !Number.isFinite(source.confidence)) return false;
  if (typeof source.summary !== "string") return false;
  if (!source.accountContext || typeof source.accountContext !== "object") return false;
  if (!Array.isArray(source.factors)) return false;
  return true;
}

function buildFallbackCommentary(report: CreativeRuleReportPayload, language: AppLanguage): CommentaryPayload {
  const positives = report.factors
    .filter((factor) => factor.impact === "positive")
    .slice(0, 3)
    .map((factor) => `${factor.label}: ${factor.reason}`);
  const risks = report.factors
    .filter((factor) => factor.impact === "negative")
    .slice(0, 3)
    .map((factor) => `${factor.label}: ${factor.reason}`);

  const summary =
    report.summary.trim().length > 0
      ? report.summary.trim()
      : language === "tr"
        ? `Rule engine bu creative için ${report.score}/100 skor ve %${Math.round(report.confidence * 100)} güven hesapladı.`
        : `Rule engine scored this creative ${report.score}/100 with ${Math.round(report.confidence * 100)}% confidence.`;

  return {
    headline:
      language === "tr"
        ? `Analiz yorumu: ${report.action.replace("_", " ").toUpperCase()}`
        : `Analysis interpretation: ${report.action.replace("_", " ").toUpperCase()}`,
    summary,
    opportunities:
      positives.length > 0
        ? positives
        : [
            language === "tr"
              ? "Skorlama modelinde belirgin bir yukari yonlu faktor tespit edilmedi."
              : "No clear upside factors were detected by the scoring model.",
          ],
    risks:
      risks.length > 0
        ? risks
        : [
            language === "tr"
              ? "Skorlama modelinde belirgin bir asagi yonlu risk isaretlenmedi."
              : "No major downside factors were flagged by the scoring model.",
          ],
    nextActions:
      report.action === "scale_hard"
        ? [
            language === "tr"
              ? "Butceyi kontrollü adimlarla artirin ve ROAS sapmasini gunluk izleyin."
              : "Increase budget in controlled steps and monitor ROAS drift daily.",
            language === "tr"
              ? "Bu konsepti benzer kitlelere taşıyın ama ROAS ve CPA için net sınırlar koyun."
              : "Duplicate this concept to adjacent audiences with guardrails.",
          ]
        : report.action === "scale"
          ? [
              language === "tr"
                ? "72 saat boyunca CPA stabilitesini doğrulayarak kademeli buyutun."
                : "Scale gradually while validating CPA stability over 72 hours.",
              language === "tr"
                ? "Yorulmaya karsi alternatif bir test creative'ini canli tutun."
                : "Keep one challenger test live to protect against fatigue.",
            ]
          : report.action === "pause" || report.action === "kill"
            ? [
                language === "tr"
                  ? "Artan harcamayı durdürün ve butceyi en iyi performans gösterenlere yonlendirin."
                  : "Stop incremental spend and redirect budget to top performers.",
                language === "tr"
                  ? "Anlamli olcude farkli bir aciyla yeni bir konsept yayinlayin."
                  : "Launch a replacement concept with a meaningfully different angle.",
              ]
            : [
                language === "tr"
                  ? "Güven artana kadar harcamayı kontrollü tutun."
                  : "Keep spend controlled until confidence improves.",
                language === "tr"
                  ? "Ek dönüşum hacmi geldikten sonra yeniden degerlendirin."
                  : "Re-evaluate after additional conversion volume.",
              ],
  };
}

function buildUserPrompt(report: CreativeRuleReportPayload, currency: string, language: AppLanguage): string {
  return JSON.stringify({
    task: "Interpret this rule-engine creative decision report for a media buyer.",
    outputSchema: {
      headline: "string, max 10 words",
      summary: "string, 1-2 sentences",
      opportunities: "string[2..3]",
      risks: "string[2..3]",
      nextActions: "string[3]",
    },
    constraints: [
      "Use only information present in the report.",
      "Do not repeat identical points across sections.",
      "Make nextActions concrete and operational.",
      `Write all narrative content in ${getAiNarrativeLanguage(language)}.`,
      getNativeNarrativeStyleInstruction(language),
      getNonTranslatableTermsInstruction(language),
    ],
    currency,
    report,
  });
}

function normalizeCommentary(payload: unknown, fallback: CommentaryPayload): CommentaryPayload {
  if (!payload || typeof payload !== "object") return fallback;
  const source = payload as Partial<CommentaryPayload>;

  const toList = (value: unknown, minCount: number, maxCount: number, backup: string[]): string[] => {
    if (!Array.isArray(value)) return backup;
    const normalized = value
      .filter((item): item is string => typeof item === "string")
      .map((item) => item.trim())
      .filter((item) => item.length > 0)
      .slice(0, maxCount);
    return normalized.length >= minCount ? normalized : backup;
  };

  return {
    headline: typeof source.headline === "string" && source.headline.trim().length > 0 ? source.headline.trim() : fallback.headline,
    summary: typeof source.summary === "string" && source.summary.trim().length > 0 ? source.summary.trim() : fallback.summary,
    opportunities: toList(source.opportunities, 2, 3, fallback.opportunities),
    risks: toList(source.risks, 2, 3, fallback.risks),
    nextActions: toList(source.nextActions, 3, 3, fallback.nextActions),
  };
}

export async function POST(request: NextRequest) {
  const payload = (await request.json().catch(() => null)) as RequestPayload | null;
  const businessId = payload?.businessId ?? null;

  const access = await requireBusinessAccess({ request, businessId });
  if ("error" in access) return access.error;

  if (isDemoBusinessId(businessId)) {
    return NextResponse.json({ ok: true, source: "ai", commentary: getDemoAiCreativeCommentary(), warning: null });
  }

  const language = await resolveRequestLanguage(request);

  const report = payload?.report;
  const currency = payload?.currency ?? "USD";

  if (!isValidReport(report)) {
    return NextResponse.json(
      {
        ok: false,
        error: "invalid_report",
        message:
          language === "tr"
            ? "Gecerli bir creative rule report payload'i gerekli."
            : "A valid rule report payload is required.",
      },
      { status: 400 }
    );
  }

  const fallback = buildFallbackCommentary(report, language);
  const messages = [
    { role: "system" as const, content: getSystemPrompt(language) },
    { role: "user" as const, content: buildUserPrompt(report, currency, language) },
  ];

  try {
    const openai = getOpenAI();
    let content = "";
    try {
      const response = await openai.chat.completions.create({
        model: MODEL,
        temperature: 0.2,
        max_tokens: 700,
        response_format: { type: "json_object" },
        messages,
      });
      content = response.choices[0]?.message?.content ?? "";
    } catch (errorWithFormat) {
      if (!isUnsupportedParameterError(errorWithFormat)) {
        throw errorWithFormat;
      }

      try {
        const responseWithoutFormat = await openai.chat.completions.create({
          model: MODEL,
          temperature: 0.2,
          max_tokens: 700,
          messages,
        });
        content = responseWithoutFormat.choices[0]?.message?.content ?? "";
      } catch (errorWithoutFormat) {
        if (!isUnsupportedParameterError(errorWithoutFormat)) {
          throw errorWithoutFormat;
        }

        const minimalResponse = await openai.chat.completions.create({
          model: MODEL,
          messages,
        });
        content = minimalResponse.choices[0]?.message?.content ?? "";
      }
    }

    const parsed = parseCommentaryJson(content);

    return NextResponse.json({
      ok: true,
      source: "ai",
      commentary: normalizeCommentary(parsed, fallback),
      warning: null,
    });
  } catch (error) {
    const raw = error instanceof Error ? error.message : "Unknown error";
    const detail = getErrorDetail(error);
    return NextResponse.json({
      ok: true,
      source: "fallback",
      commentary: fallback,
      warning: `${sanitizeErrorMessage(raw, language)} (${detail})`,
    });
  }
}
